---
version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  test:
    docker:
      - image: circleci/golang:1.13-node

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: "Run unit tests"
          environment:
            TEST_RESULTS: /tmp/test-results
          command: |
            mkdir -p $TEST_RESULTS
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  acceptance:
    docker:
      - image: circleci/golang:1.13-node

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Build binary
          command: go build -o conftest main.go
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Bats
          command: |
            cd /tmp
            curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar -xz
            sudo ./bats-0.4.0/install.sh /usr/local
      - run:
          name: Run acceptance tests
          command: |
            sudo npm install tap-xunit -g
            mkdir -p ~/reports
            bats acceptance.bats --tap | tap-xunit > ~/reports/conftest.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

  security:
    docker:
      - image: circleci/golang:1.13-node

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - snyk/scan:
          target-file: go.mod

  image:
    docker:
      - image: circleci/buildpack-deps:stretch

    parameters:
      with_snyk:
        type: boolean
        default: false

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build image
          command: docker build --pull --progress plain -t instrumenta/conftest .
          environment:
            DOCKER_BUILDKIT: 1
      - when:
          condition: <<parameters.with_snyk>>
          steps:
            - snyk/scan:
                docker-image-name: instrumenta/conftest
                project: docker.io/instrumenta/conftest
                target-file: Dockerfile

  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - test
      - acceptance
      - security:
          filters:
            branches:
              only: master
      - image:
          filters:
            branches:
              ignore: master
      - image:
          with_snyk: true
          filters:
            branches:
              only: master
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
